#!/bin/sh

# ucitrack 只对非 PROCD 程序有效
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	add ucitrack zerotier
	set ucitrack.@zerotier[-1].init='luci-zerotier'
	commit ucitrack

	delete firewall.zerotier
	set firewall.zerotier=include
	set firewall.zerotier.type=script
	set firewall.zerotier.path='/usr/share/zerotier/firewall.include'
	set firewall.zerotier.reload=1
	commit firewall
EOF

# 确保 RPC 脚本有执行权限
[ -f /usr/libexec/rpcd/luci-zerotier ] && chmod +x /usr/libexec/rpcd/luci-zerotier

# 重启 rpcd 加载新的 RPC 方法
[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd restart

# 重启 uhttpd 确保 LuCI 加载新文件
[ -x /etc/init.d/uhttpd ] && /etc/init.d/uhttpd restart

rm -f /tmp/luci-indexcache
exit 0
